"""Reusable inference components for QuzhouAITrials."""

from .decision_engine import DecisionEngine, DecisionEngineError, DecisionSlot
from .decision_contract import (
    DECISION_RESULT_SCHEMA_VERSION,
    DECISION_RESULT_TOP_LEVEL_KEYS,
    build_decision_result,
    json_safe,
    sanitize_model_metadata,
    serialize_decision_error,
)
from .errors import (
    DecisionDomainError,
    RequestValidationError,
    QueryDateBeforeCropStartError,
    QueryDateAfterCropEndError,
    IncompleteFertilizationHistoryError,
    UnrepresentableNRateError,
    UnrepresentableFertilizationDateError,
    UnsupportedResidualPeriodManagementError,
    CustomIrrigationNotSupportedError,
    ObservationDateMismatchError,
    ModelArtifactMissingError,
    ModelEnvironmentIncompatibleError,
    WeatherProviderError,
    DynamicCalendarInvalidError,
    ManagementEventInvalidError,
    WeatherProviderNotConfiguredError,
    WeatherDataGapError,
    WeatherTimelineInvalidError,
    ForecastHorizonInsufficientError,
    WeatherLiveQueryDayUnavailableError,
    ForwardSimulationError,
    ScenarioEvaluationError,
)
from .observation_fusion import ObservationFusionEngine, ObservationFusionError
from .rl_inference import (
    RLInferenceEngine,
    action_index_to_n_rate,
)
from .management_history import (
    ManagementHistoryError,
    build_action_history,
    management_to_realtime_input,
)
from .schemas import (
    SCHEMA_VERSION,
    Crop,
    CropObservation,
    DecisionContext,
    DecisionRequest,
    FertilizationEvent,
    IrrigationEvent,
    Location,
    ManagementHistory,
    ObservationSnapshot,
    ObservationSource,
    RequestContext,
    SchemaValidationError,
    SoilLayerObservation,
    Weather,
    WeatherObservation,
    get_schema_capabilities,
    normalize_decision_request,
)
from .wofost_realtime import WOFOSTRealtimeEngine
from .season_calendar import DynamicCalendarError, SeasonCalendar, SeasonCalendarResolver
from .management_events import (
    ManagementEventError,
    ManagementTimeline,
    FertilizerEvent as DynamicFertilizerEvent,
    IrrigationEvent as DynamicIrrigationEvent,
)
from .weather_records import WeatherDataKind, WeatherRecord, WeatherRecordError
from .weather_service import HistoricalForecastTimelineBuilder, WeatherService
from .weather_providers import TimelineWeatherDataProvider
from .forward_simulation import ForwardSimulationResult, ForwardSimulator
from .scenario_evaluation import ManagementScenario, ScenarioEvaluator, ScenarioGenerator
from .weather_risk import WeatherRiskEvaluator, WeatherRiskThresholds
from .operation_advice import OperationAdvice
from .soil_observation import (
    ModelSoilLayer,
    SoilObservationAdapter,
    SoilObservationError,
    mg_n_kg_to_kg_ha,
    volumetric_water_to_cm_water,
)

__all__ = [
    "SCHEMA_VERSION",
    "Crop",
    "CropObservation",
    "DecisionEngine",
    "DecisionEngineError",
    "DecisionDomainError",
    "DecisionContext",
    "DecisionRequest",
    "DecisionSlot",
    "DECISION_RESULT_SCHEMA_VERSION",
    "DECISION_RESULT_TOP_LEVEL_KEYS",
    "ObservationFusionEngine",
    "ObservationFusionError",
    "RequestValidationError",
    "QueryDateBeforeCropStartError",
    "QueryDateAfterCropEndError",
    "IncompleteFertilizationHistoryError",
    "UnrepresentableNRateError",
    "UnrepresentableFertilizationDateError",
    "UnsupportedResidualPeriodManagementError",
    "CustomIrrigationNotSupportedError",
    "ObservationDateMismatchError",
    "ModelArtifactMissingError",
    "ModelEnvironmentIncompatibleError",
    "WeatherProviderError",
    "DynamicCalendarInvalidError",
    "ManagementEventInvalidError",
    "WeatherProviderNotConfiguredError",
    "WeatherDataGapError",
    "WeatherTimelineInvalidError",
    "ForecastHorizonInsufficientError",
    "WeatherLiveQueryDayUnavailableError",
    "ForwardSimulationError",
    "ScenarioEvaluationError",
    "FertilizationEvent",
    "IrrigationEvent",
    "Location",
    "ManagementHistory",
    "ManagementHistoryError",
    "ObservationSnapshot",
    "ObservationSource",
    "RLInferenceEngine",
    "RequestContext",
    "SchemaValidationError",
    "SoilLayerObservation",
    "Weather",
    "WeatherObservation",
    "WOFOSTRealtimeEngine",
    "DynamicCalendarError",
    "SeasonCalendar",
    "SeasonCalendarResolver",
    "ManagementEventError",
    "ManagementTimeline",
    "DynamicFertilizerEvent",
    "DynamicIrrigationEvent",
    "WeatherDataKind",
    "WeatherRecord",
    "WeatherRecordError",
    "HistoricalForecastTimelineBuilder",
    "WeatherService",
    "TimelineWeatherDataProvider",
    "ForwardSimulationResult",
    "ForwardSimulator",
    "ManagementScenario",
    "ScenarioEvaluator",
    "ScenarioGenerator",
    "WeatherRiskEvaluator",
    "WeatherRiskThresholds",
    "OperationAdvice",
    "action_index_to_n_rate",
    "build_decision_result",
    "build_action_history",
    "get_schema_capabilities",
    "management_to_realtime_input",
    "normalize_decision_request",
    "json_safe",
    "sanitize_model_metadata",
    "serialize_decision_error",
    "ModelSoilLayer",
    "SoilObservationAdapter",
    "SoilObservationError",
    "mg_n_kg_to_kg_ha",
    "volumetric_water_to_cm_water",
]
